name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2
      # Use Bun
      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.38
      # Install
      - name: Install
        run: bun install
      # Build
      - name: Build
        run: bun run build
